DELIMITER //
DROP PROCEDURE IF EXISTS GET_ALL_WORKERS;
CREATE PROCEDURE GET_ALL_WORKERS()
BEGIN
	SELECT WORKER.ID, WORKER.FIRSTNAME, WORKER.LASTNAME, WORKER.CARDNUMBER, POSITION.POSITION, WORKER.ISACTIVE 
		FROM POSITION JOIN WORKER ON POSITION.ID=WORKER.POSITIONID;
END; //
DELIMITER ;