DELIMITER //
DROP PROCEDURE IF EXISTS SAVE_WEB_TOKEN;
CREATE PROCEDURE SAVE_WEB_TOKEN(IN workerId int)
BEGIN
	DECLARE token VARCHAR(20);
    SELECT "" INTO token;
    
    WHILE LENGTH(token) < 20 DO
		SELECT CONCAT(token, (CHAR(FLOOR(97 + (RAND() * 25))))) into token ;
    END WHILE;
    
	INSERT INTO SESSIONTOKENS (WORKERID, DATE, TOKEN) VALUES (workerId, now(), token);
END; //
DELIMITER ;
