DELIMITER //
DROP PROCEDURE IF EXISTS SELECT_MONTH_TIME_RAPORT;
CREATE PROCEDURE SELECT_MONTH_TIME_RAPORT(IN WORKER_ID INT, IN CURRENT_MONTH INT)
BEGIN
	SELECT WORKDAY.ID, PROJECT.GENUMBER, PROJECT.RONUMBER, PROJECT.DESCRIPTION, WORKDAY.STARTTIME, WORKDAY.STOPTIME, TIMESTAMPDIFF(MINUTE, IFNULL(WORKDAY.STARTTIME, NOW()), WORKDAY.STOPTIME) 
		AS WORKEDTIME 
		FROM WORKDAY INNER JOIN PROJECT ON WORKDAY.PROJECTID = PROJECT.ID
        WHERE WORKDAY.WORKERID = WORKER_ID;
END; //
DELIMITER ;