# RETURNS THE STATUS: INACTIVE, ACTIVE, BREACK AND NUMBER OF MINUTES WORKED IN THE CURRENT DAY
DELIMITER //
DROP PROCEDURE IF EXISTS SELECT_WORKER_STATUS;
CREATE PROCEDURE SELECT_WORKER_STATUS(IN WORKER_ID INT)
BEGIN
	DECLARE worker_status varchar(10) DEFAULT "INACTIVE";
    DECLARE time_worked_today int;
    
    # DETERMINE WORKER'S STATUS
    IF (SELECT ISACTIVE FROM WORKER WHERE ID = WORKER_ID) 
    THEN
		SELECT "BREAK" INTO worker_status;
		IF (SELECT ID FROM WORKDAY WHERE WORKERID = WORKER_ID AND STARTTIME IS NOT NULL AND STOPTIME IS NULL)
        THEN 
			SELECT "ACTIVE" INTO worker_status;
		END IF;
    END IF;
    
    # DETERMINE HOW MANY SECONDS THE WORKER WORKED TODAY
    SELECT worker_status UNION SELECT TIMESTAMPDIFF(MINUTE, (IFNULL(WORKDAY.STARTTIME, NOW())), WORKDAY.STOPTIME) 
		FROM WORKDAY 
        WHERE YEAR(STARTTIME) = YEAR(NOW()) AND DAYOFYEAR(STARTTIME) = DAYOFYEAR(NOW()) AND WORKERID = WORKER_ID;
END; //
DELIMITER ;